apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: advanced-object-search-bundle
    description: Advanced Object Search bundle provides advanced object search in
        OpenDXP backend powered by OpenSearch.
spec:
    type: library
    lifecycle: production
    owner: team-opendxp
    system: opendxp
