<?php

/**
 * OpenDXP
 *
 * This source file is licensed under the GNU General Public License version 3 (GPLv3).
 *
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 * @copyright  Copyright (c) Pimcore GmbH (https://pimcore.com)
 * @copyright  Modification Copyright (c) OpenDXP (https://www.opendxp.io)
 * @license    https://www.gnu.org/licenses/gpl-3.0.html  GNU General Public License version 3 (GPLv3)
 */

namespace OpenDxp\Bundle\AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter;

use ONGR\ElasticsearchDSL\BuilderInterface;
use ONGR\ElasticsearchDSL\Query\Compound\BoolQuery;
use ONGR\ElasticsearchDSL\Query\Joining\NestedQuery;
use OpenDxp\Bundle\AdvancedObjectSearchBundle\Filter\FieldSelectionInformation;
use OpenDxp\Bundle\AdvancedObjectSearchBundle\Filter\FilterEntry;
use OpenDxp\Model\DataObject\ClassDefinition\Data;
use OpenDxp\Model\DataObject\Concrete;
use OpenDxp\Tool;
use Override;

class Localizedfields extends DefaultAdapter implements FieldDefinitionAdapterInterface
{
    /**
     * @var Data\Localizedfields
     */
    protected $fieldDefinition;

    /**
     * @return array
     */
    #[Override]
    public function getESMapping()
    {
        $children = $this->fieldDefinition->getFieldDefinitions();
        $childMappingProperties = [];
        foreach ($children as $child) {
            $fieldDefinitionAdapter = $this->service->getFieldDefinitionAdapter($child, $this->considerInheritance);
            [$key, $mappingEntry] = $fieldDefinitionAdapter->getESMapping();
            $childMappingProperties[$key] = $mappingEntry;
        }

        $mappingProperties = [];
        $languages = Tool::getValidLanguages();
        foreach ($languages as $language) {
            $mappingProperties[$language] = [
                'type' => 'nested',
                'properties' => $childMappingProperties,
            ];
        }

        return [
            $this->fieldDefinition->getName(),
            [
                'type' => 'nested',
                'properties' => $mappingProperties,
            ],
        ];
    }

    /**
     * @param Concrete $object
     *
     * @return array
     */
    #[Override]
    public function getIndexData($object)
    {
        $localeBackup = $this->localeService->getLocale();

        $validLanguages = Tool::getValidLanguages();

        $localizedFieldData = [];

        if ($validLanguages) {
            foreach ($validLanguages as $language) {
                foreach ($this->fieldDefinition->getFieldDefinitions() as $key => $fieldDefinition) {
                    $this->localeService->setLocale($language);

                    $fieldDefinitionAdapter = $this->service->getFieldDefinitionAdapter($fieldDefinition, $this->considerInheritance);
                    $localizedFieldData[$language][$key] = $fieldDefinitionAdapter->getIndexData($object);
                }
            }
        }

        $this->localeService->setLocale($localeBackup);

        return $localizedFieldData;
    }

    /**
     * @param array $fieldFilter
     *
     * filter field format as follows:
     *  stdObject with language as key and languageFilter array as values like
     *    [
     *      'en' => FilterEntry[]  - FULL FEATURES FILTER ENTRY ARRAY
     *    ]
     *   e.g.
     *      'en' => [
     *          ["fieldnme" => "locname", "filterEntryData" => "englname"]
     *       ]
     * @param bool $ignoreInheritance
     * @param string $path
     *
     * @return BuilderInterface
     */
    #[Override]
    public function getQueryPart($fieldFilter, $ignoreInheritance = false, $path = '')
    {
        $languageQueries = [];

        foreach ($fieldFilter as $language => $languageFilters) {
            $path = $path . $this->fieldDefinition->getName() . '.' . $language;
            $languageBoolQuery = new BoolQuery();

            foreach ($languageFilters as $localizedFieldFilter) {
                $filterEntryObject = $this->service->buildFilterEntryObject($localizedFieldFilter);

                if ($filterEntryObject->getFilterEntryData() instanceof BuilderInterface) {

                    // add given builder interface without any further processing
                    $languageBoolQuery->add($filterEntryObject->getFilterEntryData(), $filterEntryObject->getOuterOperator());
                } else {
                    $fieldDefinition = $this->fieldDefinition->getFielddefinition($filterEntryObject->getFieldname());
                    $fieldDefinitionAdapter = $this->service->getFieldDefinitionAdapter($fieldDefinition, $this->considerInheritance);

                    if ($filterEntryObject->getOperator() == FilterEntry::EXISTS || $filterEntryObject->getOperator() == FilterEntry::NOT_EXISTS) {

                        //add exists filter generated by filter definition adapter
                        $languageBoolQuery->add(
                            $fieldDefinitionAdapter->getExistsFilter($filterEntryObject->getFilterEntryData(), $filterEntryObject->getIgnoreInheritance(), $path . '.'),
                            $filterEntryObject->getOuterOperator()
                        );
                    } else {

                        //add query part generated by filter definition adapter
                        $languageBoolQuery->add(
                            $fieldDefinitionAdapter->getQueryPart($filterEntryObject->getFilterEntryData(), $filterEntryObject->getIgnoreInheritance(), $path . '.'),
                            $filterEntryObject->getOuterOperator()
                        );
                    }
                }
            }
            $languageQueries[] = new NestedQuery($path, $languageBoolQuery);
        }

        if (count($languageQueries) == 1) {
            return $languageQueries[0];
        } else {
            $boolQuery = new BoolQuery();
            foreach ($languageQueries as $query) {
                $boolQuery->add($query);
            }

            return $boolQuery;
        }
    }

    /**
     * returns selectable fields with their type information for search frontend
     *
     * @return FieldSelectionInformation[]
     */
    #[Override]
    public function getFieldSelectionInformation()
    {
        $fieldSelectionInformationEntries = [];

        $children = $this->fieldDefinition->getFieldDefinitions();
        foreach ($children as $child) {
            $fieldDefinitionAdapter = $this->service->getFieldDefinitionAdapter($child, $this->considerInheritance);

            $subEntries = $fieldDefinitionAdapter->getFieldSelectionInformation();
            foreach ($subEntries as $subEntry) {
                $context = $subEntry->getContext();
                $context['subType'] = $subEntry->getFieldType();
                $context['languages'] = Tool::getValidLanguages();
                $subEntry->setContext($context);

                $subEntry->setFieldType('localizedfields');
            }

            $fieldSelectionInformationEntries = array_merge($fieldSelectionInformationEntries, $subEntries);
        }

        return $fieldSelectionInformationEntries;
    }
}
